# Generated by Django 5.2.10 on 2026-01-16 04:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenaza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('Interna', 'Interna'), ('Externa', 'Externa')], max_length=20)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProyectoEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo_organizacion', models.CharField(max_length=100)),
                ('responsable', models.CharField(max_length=150)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vulnerabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('Técnica', 'Técnica'), ('Configuración', 'Configuración'), ('Proceso', 'Proceso'), ('Humana', 'Humana')], max_length=30)),
                ('criterio_deteccion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ActivoDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('Dominio', 'Dominio'), ('Subdominio', 'Subdominio'), ('IP Pública', 'IP Pública'), ('Servicio Expuesto', 'Servicio Expuesto'), ('Aplicación Web', 'Aplicación Web'), ('API', 'API'), ('Repositorio Público', 'Repositorio Público'), ('Certificado Digital', 'Certificado Digital'), ('Archivo Indexado', 'Archivo Indexado'), ('Credencial Filtrada', 'Credencial Filtrada')], max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('c', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('i', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('d', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('cia_promedio', models.DecimalField(decimal_places=2, editable=False, max_digits=3)),
                ('nivel_criticidad', models.CharField(max_length=20)),
                ('fuente_osint', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Desconocido', 'Desconocido')], max_length=20)),
                ('fecha_identificacion', models.DateField(auto_now_add=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activos', to='core.proyectoevaluacion')),
            ],
        ),
        migrations.CreateModel(
            name='Riesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probabilidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('impacto', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('nivel_riesgo', models.IntegerField(editable=False)),
                ('probabilidad_residual', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('impacto_residual', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('nivel_riesgo_residual', models.IntegerField(blank=True, null=True)),
                ('nivel_prioridad', models.CharField(max_length=20)),
                ('estado', models.CharField(choices=[('Abierto', 'Abierto'), ('En tratamiento', 'En tratamiento'), ('Cerrado', 'Cerrado')], max_length=20)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riesgos', to='core.activodigital')),
                ('amenaza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.amenaza')),
                ('vulnerabilidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.vulnerabilidad')),
            ],
        ),
        migrations.CreateModel(
            name='TratamientoRiesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrategia', models.CharField(choices=[('Mitigar', 'Mitigar'), ('Transferir', 'Transferir'), ('Aceptar', 'Aceptar'), ('Evitar', 'Evitar')], max_length=20)),
                ('descripcion_control', models.TextField()),
                ('control_iso_27002', models.CharField(max_length=100)),
                ('responsable', models.CharField(max_length=150)),
                ('fecha_implementacion', models.DateField()),
                ('riesgo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tratamiento', to='core.riesgo')),
            ],
        ),
    ]
