# Generated by Django 5.2.10 on 2026-01-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riesgo',
            name='estado',
            field=models.CharField(choices=[('Abierto', 'Abierto'), ('En tratamiento', 'En tratamiento'), ('Cerrado', 'Cerrado')], default='Abierto', max_length=20),
        ),
        migrations.AlterField(
            model_name='riesgo',
            name='nivel_prioridad',
            field=models.CharField(editable=False, max_length=10),
        ),
    ]
